### ISSUE TITLE
Add utility methods to build, sign, and send a transaction

### ISSUE THREAD

**Issue by s8sato** [hyperledger/iroha-javascript#113]
Add utility methods to build, sign, and send a transaction. Something like:

- [x] ~`createTransactionPayload`~
  - The request was canceled because your example helped them @0x009922 
- [ ] `signTransactionPayload`
- [ ] `submitVersionedTransaction`

**Comment by 0x009922** [comment]
- `createTransactionPayload` - what exactly is needed here? Transaction payload could be created by hand with `TransactionPayload()` helper from `@iroha2/data-model`:

  ```ts
  import { TransactionPayload, OptionU32, MapNameValue } from '@iroha2/data-model'

  const payload = TransactionPayload({
    instructions: executable,
    time_to_live_ms: 100_000n,
    nonce: OptionU32('None'),
    metadata: MapNameValue(new Map()),
    creation_time: BigInt(Date.now()),
    account_id: accountId,
  })
  ```

- `signTransactionPayload` - this could be exposed easily. Currently `Client.submit()` does it internally.
- `submitVersionedTransaction` - this could be exposed from `Client` as well.

**Comment by s8sato** [comment]
The [transaction lifecycle feature](https://github.com/hyperledger/iroha/issues/2478) will affect the implementation of this issue

**Comment by 0x009922** [comment]
I close this issue after merging of #124.

- You can scaffold a transaction payload with a new helper for it - `makeTransactionPayload()`
- You can make signature of a transaction in 2 ways:
  - `signTransaction(payload)` returns `Signature`
  - `makeSignedTransaction(payload, signer)` returns signed `VersionedTransaction`
- `Torii.transaction(tx)` literally only submits `VersionedTransaction`
