### ISSUE TITLE
Move grpc from devDependencies to dependencies

### ISSUE THREAD

**Issue by outSH** [hyperledger/iroha-javascript#173]
`grpc` is a dependency of `iroha-helpers` (irohaV1) but it's listed under `devDependencies` instead of `dependencies`. This causes error when user doesn't have grpc installed. Issue occured at our project (Hyperledger Cacti) when we updated from deprecated [grpc](https://www.npmjs.com/package/grpc) to [grpc-js](https://www.npmjs.com/package/@grpc/grpc-js).

To reproduce initialize empty TS nodejs project, `npm i iroha-helpers` (only), compile the following:

``` typescript
import { QueryService_v1Client as QueryService } from "iroha-helpers/lib/proto/endpoint_grpc_pb";

console.log(QueryService.toString());
```

And run. Error printed:

``` sh
Error: Cannot find module 'grpc'
Require stack:
- /home/vagrant/tmp/iroha-check/node_modules/iroha-helpers/lib/proto/endpoint_grpc_pb.js
- /home/vagrant/tmp/iroha-check/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/vagrant/tmp/iroha-check/node_modules/iroha-helpers/lib/proto/endpoint_grpc_pb.js:9:12)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/vagrant/tmp/iroha-check/node_modules/iroha-helpers/lib/proto/endpoint_grpc_pb.js',
    '/home/vagrant/tmp/iroha-check/index.js'
  ]
}
```

**Comment by petermetz** [comment]
I recommend migrating to the new, purely JS implementation instead because the legacy `grpc` package has been deprecated for a long time now:

![image](https://github.com/hyperledger/iroha-javascript/assets/1583231/de64e88e-bc92-41c5-b04a-a26a9f2ac858)

**Comment by outSH** [comment]
@6r1d @0x009922 Any updates regarding this? It's blocking our CI at the moment. Let us know if this package is still supported and can have grpc fixed / updated in the nearest future. If it's deprecated (or is about to be), then we could remove support for Iroha V1 from cacti.

**Comment by 0x009922** [comment]
Hi @outSH 
I cannot help you with the functionality related to Iroha 1, unfortunately.

@6r1d, what about support of Iroha 1 in cacti?

**Comment by 6r1d** [comment]
I apologize, but I still have no updates about the Iroha 1 security support process. I will re-raise this question today.

**Comment by 6r1d** [comment]
@outSH  I will update you as soon as I get the decision on that matter.

**Comment by outSH** [comment]
@6r1d Thanks for looking into that, any news so far?

**Comment by baziorek** [comment]
@6r1d @outSH I'm not javascript expert, but if I understand You correctly if I edit the file:
https://github.com/hyperledger/iroha-javascript/blob/main/package.json
and I copy line:
https://github.com/hyperledger/iroha-javascript/blob/3215805a0c7f53ed9d551fe6b09db8e031d9d024/package.json#L61
under line (into `dependencies` section):
https://github.com/hyperledger/iroha-javascript/blob/3215805a0c7f53ed9d551fe6b09db8e031d9d024/package.json#L35

it will fix first problem?

________________________
And next problem will be fixed if I replace:
`"grpc": "^1.22.2",` into `"grpc-js":"^1.9.0"` and make sure that the library is working it will solve another problem?

Am I correct?

**Comment by petermetz** [comment]
@6r1d This might help a little bit (but do let me know if it doesn't). The migration from `grpc` to `grpc/grpc-js` is meant to be fairly straightforward. What I mean by that is that when I was migrating parts of the Cacti codebase the same way, 99% of the time the only thing I needed to do was to replace the package imports in the code and everything would just work fine out of the box afterwards. There was no need to refactor the code and risk introducing new bugs, etc.

**Comment by petermetz** [comment]
@6r1d I just ended up sending in a quick PR. It's a pretty simple change. I verified that it works with our Cacti Iroha connector tests.
See my PR: https://github.com/hyperledger/iroha-javascript/pull/182

**Comment by outSH** [comment]
@6r1d @0x009922 Hi, do you plan to release a version containing this fix?

**Comment by outSH** [comment]
@6r1d @0x009922 any news regarding releasing new version with that fix? :)

**Comment by 0x009922** [comment]
@outSH, created a task for it: #189
