### ISSUE TITLE
Unexpected type (Quantity / Fixed)

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-javascript#179]
Matías Salimbene reported an [issue](https://t.me/hyperledgeriroha/30343) with types in Iroha JS SDK today.

```
Transaction validation failed reason=Validation failed caused_by=Some(InstructionFailed(Evaluate(Type(AssetValueType(Mismatch { expected: Fixed, actual: Quantity })))))
```

The valueType is correctly registered as `Quantity` (not Fixed).

```json
    "value_type": {
        "enum": {
            "tag": "Quantity"
        }
    }
```

Additionaly, Matías gets an error if he doesn't provide the quantity with decimal precision, i.e `quantity: "100"` fails, but `quantity:"100.0"` is fine. He'd like to know whether this should be expected.

Provided context:

* Peer: `stable-2.0.0-pre-rc.20`
* `client/data model`: `^7.0.0`

**Comment by a1salimbene** [comment]
I found the problem, I was following an example from the unit tests that created value as `Fixed`, instead of `numericU32`.

Now I can pass quantity as number: "quantity": 100.0, I had to define the value as numericU32 to be parsed correctly.
