### ISSUE TITLE
Broken demo link

### ISSUE THREAD

**Issue by djKooks** [hyperledger/iroha-javascript#23]
It seems demo link has been broken on README.
Where can I find it?

**Comment by robinleboe-sw** [comment]
The demo link is still broken.

**Comment by stinger112** [comment]
@djKooks @robinleboe-sw 

This project isn't maintained anymore, but you can install [our new library](https://www.npmjs.com/package/iroha-lib) by NPM or watch source code in main Iroha repo. For now, it placed [here](https://github.com/hyperledger/iroha/tree/develop/shared_model/packages/javascript) (internal path can be changed).

Please, ask your future questions in Iroha repository.

Best wishes,
Arseniy Fokin.
