### ISSUE TITLE
Is this library still being maintained?

### ISSUE THREAD

**Issue by RobTS** [hyperledger/iroha-javascript#25]
Last commit was nine months ago, the link to the latest release is not working and you can't even import it into a vanilla node.js project using the github url due to the fact that there's only a .ts file.

Is this project (and HL Iroha along with it) going anywhere?

**Comment by stinger112** [comment]
@RobTS this project isn't maintained anymore, but you can install [our new library](https://www.npmjs.com/package/iroha-lib) by NPM or watch source code in main Iroha repo. For now, it placed [here](https://github.com/hyperledger/iroha/tree/develop/shared_model/packages/javascript) (internal path can be changed).

Please, ask your future questions in Iroha repository. 

Best wishes, 
Arseniy Fokin.
