### ISSUE TITLE
[Q] will this package works in react native?

### ISSUE THREAD

**Issue by valinaga** [hyperledger/iroha-javascript#26]
Hi,

Can anyone confirm or infirm if this package works with react native?
Thanks

**Comment by stinger112** [comment]
@valinaga 
Hi! This project isn't maintained anymore, we created new lib in [main Iroha repo](https://github.com/hyperledger/iroha/tree/develop/shared_model/packages/javascript)

AFAIK, C++ native part of new **iroha-lib** NPM package doesn't support compilation on ARM architecture, so it can't work with react-native. But we work on portability of native part and maybe it can be realized in compilation scenario in the future.

Please, ask your future questions in Iroha repository.

Best wishes,
Arseniy Fokin.
