### ISSUE TITLE
convert to grpc+flatbuffers

### ISSUE THREAD

**Issue by takemiyamakoto** [hyperledger/iroha-javascript#9]
The SDK needs to be built to work with grpc and handle flatbuffers natively 

see: https://github.com/grpc/grpc-experiments/issues/159

**Comment by theofilis** [comment]
Hello, I've started implementation of gRPC client. First it will support NodeJS then I will try to port it at browser.

**Comment by takemiyamakoto** [comment]
This is the latest flatbuffer format: https://gist.github.com/Warchant/b7049e2f0653bd30c78f06b283c30bf0/revisions#diff-81f138be4276f4ba228e0164d8d7b773R27

**Comment by luca3104** [comment]
@theofilis How is the progress?

**Comment by theofilis** [comment]
Hi, I manage to create a client with gRPC+protobuff, although I haven't have any significant progress with flatbuff. 

I started gRPC+protobuff in order to I become familiar with gRPC. 

Guy, if you found any helpful material for gRPC+flatbuffer don't hesitate to share it.

**Comment by stinger112** [comment]
Issue is outdated.
